Nep 896 generate vp on wallet
affinityproject/affinidi-interop-test-service pull request #32
Opened 2020-12-16 21:27 UTC by afshanaman81

The wallet app can now generate VPs locally

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (non-code change, i.e. new architecture decision definition)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have covered my changes with the necessary unit tests and endpoint tests

2020-12-16 22:33 UTC, JaceHensley requested changes

2020-12-16 22:33 UTC, JaceHensley commented on apps/wallet/components/BarcodeScanner.js
> +			.then(async (response) => {
Does this need to be async? Doesn't look like anything is being `await`ed

2020-12-16 22:33 UTC, JaceHensley commented on apps/wallet/components/BarcodeScanner.js
> +					console.log(msg);
#nit remove log

2020-12-16 22:33 UTC, JaceHensley commented on apps/wallet/components/BarcodeScanner.js
> +		console.log(msg);
#nit remove log

2020-12-16 22:33 UTC, JaceHensley commented on apps/wallet/components/DisplayCredentials.js
> +		this.getResultsFromDB();
Don't setState in render, if you want this to be done on mount put it in `componentDidMount` or if you want to to trigger on an update use `componentDidUpdate` but you'll want to put it behind a conditional or else you'll end up with an infinite loop. https://reactjs.org/docs/react-component.html#componentdidupdate

2020-12-16 22:38 UTC, afshanaman81 commented on apps/wallet/components/DisplayCredentials.js
> +		this.getResultsFromDB();
its in the `componentDidMount` already. Needed it to refresh every time we came to this screen. 

So I will add the `componentDidUpdate`

2020-12-16 23:12 UTC, JaceHensley commented on apps/wallet/components/DisplayCredentials.js
> +		this.getResultsFromDB();
Alternatively you could set this on the `Tab.Screen` to make it remount every time you go to the screen `options={{unmountOnBlur: true}}`

2020-12-17 08:56 UTC, DenisPopov15 requested changes

2020-12-17 08:56 UTC, DenisPopov15 commented on apps/wallet/components/BarcodeScanner.js
> +					const result = await Database.getCredentialsById(tableName, 1);
@afshanaman81 what will happens if there is no credentials in the wallet, or there is no credentials requested types, etc, also where is the guarantee, that on credentials by id: 1 will be required credential?

Lets do it in generic way. You should parse challenge (JWT) token, get types from there and make proper DB query and raise proper alert if there is no match.
e.g. at the SDK (if use Affinidi wallet for storing credentials) - we have there optional reuqestToken parameter for pulling credentials (which will filter them by request types): https://github.com/affinityproject/affinidi-core-sdk/tree/master/sdk/expo#pull-credential-from-vc-vault

2020-12-18 21:54 UTC, JaceHensley approved these changes

2020-12-19 08:25 UTC, DenisPopov15 approved these changes

2020-12-19 08:25 UTC, DenisPopov15 commented on apps/wallet/components/BarcodeScanner.js
> +		const types = decoded.interactionToken.credentialRequirements[0].type;
@afshanaman81 lets have it as is, but lets left a comment, that for all cases functionality this query should be updated (since at the request token could be required several different credentials, also types[1] will work only for this particular use case, ideally query should pull all VCs, which have included at type field array all elements from the requirement entry of the request, e.g. at the DB there is an VC with type: ['VerifiableCredential', 'EmailPersonV1'], and at the credentialRequirement entry of the credentialRequirements request array type is: ['VerifiableCredential', 'EmailPersonV1', 'RevocationList2020'], so in such case no creentials should be found/returned), but as I mentioned we fine to keep it as it is, but lets add TODO at the code here

2020-12-20 02:50 UTC, afshanaman81 commented on apps/wallet/components/BarcodeScanner.js
> +		const types = decoded.interactionToken.credentialRequirements[0].type;
I think, in a real application, developers should build any custom query to fetch the Credentials as needed.
What is provided is just a simple example query. Additional methods, similar to the getCredentialsByType(), can be implemented in the DBService, according to the application needs

2020-12-20 03:07 UTC, merged